<a href="https://colab.research.google.com/github/Dhnxz/New-project/blob/main/uber_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv('uber_delivery_tips_dataset.csv')

In [4]:
result1 = df[(df['earnings'] > 25) & (df['tip'] > 3)]
result1

,date,time,fare,tip,earnings,distance,duration,restaurant_address,points,deliveries_count,...,weekday_name,is_weekend,is_holiday,duration_min,speed_mph,part_of_day,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
5,2025-03-09,1.5,13.87,16.67,30.54,9.95,50 min 00 s,Jack in the Box (501 N Milpas St),3,3,...,Sunday,True,False,50.000000,11.940000,Night,3.069347,36.648000,0.545842,1
15,2025-08-01,19.5,9.15,20.11,29.26,10.12,45 min 3 sec,Chipotle Mexican Grill (3851 State St),18,3,...,Friday,False,False,45.050000,13.478357,Evening,2.891304,38.970033,0.687286,1
35,2025-05-01,18.0,13.47,15.42,28.89,18.79,1 hr 0 min,St. Bibiana,12,2,...,Thursday,False,False,60.000000,18.790000,Evening,1.537520,28.890000,0.533749,0
56,2025-08-10,18.5,5.77,37.73,43.50,3.21,39 min 29 sec,Sachi Ramen (Santa Barbara),18,3,...,Sunday,True,False,39.483333,4.878008,Evening,13.551402,66.103841,0.867356,1
57,2025-08-10,19.5,11.06,22.20,33.26,9.86,42 min 13 sec,Poke House (Santa Barbara),12,3,...,Sunday,True,False,42.216667,14.013423,Evening,3.373225,47.270430,0.667468,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,2025-09-07,17.5,18.20,16.48,34.68,18.37,1h 16m,Shang Hai,18,3,...,Sunday,True,False,16.000000,68.887500,Afternoon,1.887861,130.050000,0.475202,1
1146,2025-09-07,19.0,21.66,7.90,29.56,12.72,1h 06m,Hummus Republic – Isla Vista,18,2,...,Sunday,True,False,6.000000,127.200000,Evening,2.323899,295.600000,0.267253,1
1162,2025-08-08,19.0,8.78,19.68,28.46,3.86,30 min 50 sec,Bruxie (Santa Barbara),18,3,...,Friday,False,False,30.833333,7.511351,Evening,7.373057,55.381622,0.691497,1
1171,2025-06-08,18.5,10.66,20.45,31.11,5.92,51m 26s,Apna Indian Kitchen (Santa Barbara),18,3,...,Sunday,True,False,51.433333,6.906027,Evening,5.255068,36.291640,0.657345,1
1213,2025-09-09,23.0,33.50,9.00,42.50,16.99,49m 10s,Jack in the Box (501 N Milpas St),2,2,...,Tuesday,False,False,49.166667,20.733559,Night,2.501471,51.864407,0.211765,1

In [5]:
result2 = df[df['part_of_day'].str.contains('Night', case=False)]
result2

,date,time,fare,tip,earnings,distance,duration,restaurant_address,points,deliveries_count,...,weekday_name,is_weekend,is_holiday,duration_min,speed_mph,part_of_day,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
1,2025-03-08,0.0,5.93,2.00,7.93,2.59,23 min 36 s,"McDonald's, Cliff Dr",2,1,...,Saturday,True,False,23.600000,6.584746,Night,3.061776,20.161017,0.252207,1
4,2025-03-09,1.0,2.65,6.44,9.09,1.59,12 min 05 s,"Taco Bell, 821 N Milpas St",1,1,...,Sunday,True,False,12.083333,7.895172,Night,5.716981,45.136552,0.708471,1
5,2025-03-09,1.5,13.87,16.67,30.54,9.95,50 min 00 s,Jack in the Box (501 N Milpas St),3,3,...,Sunday,True,False,50.000000,11.940000,Night,3.069347,36.648000,0.545842,1
7,2025-08-01,0.5,3.44,6.05,9.49,4.58,13 min 10 sec,McDonald's (29 N Milpas St),1,1,...,Friday,False,False,13.166667,20.870886,Night,2.072052,43.245570,0.637513,1
8,2025-08-01,1.0,4.18,11.24,15.42,3.37,32 min 10 sec,"Taco Bell, 821 N Milpas St",2,2,...,Friday,False,False,32.166667,6.286010,Night,4.575668,28.762694,0.728923,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,2025-03-08,2.5,8.90,7.17,16.07,2.81,26m 19s,Breakfast Beauties (6553 Pardall Rd),2,2,...,Saturday,True,False,26.316667,6.406586,Night,5.718861,36.638379,0.446173,1
1187,2025-09-08,23.5,4.64,3.40,8.04,4.44,37m 01s,7-Eleven (7390 Calle Real),1,1,...,Monday,False,False,37.016667,7.196758,Night,1.810811,13.031968,0.422886,1
1201,2025-07-09,23.0,6.87,8.95,15.82,2.77,41m 15s,Taco Bell (1840 Cliff Dr),2,1,...,Wednesday,False,False,41.250000,4.029091,Night,5.711191,23.010909,0.565740,1
1212,2025-09-09,22.5,6.25,0.00,6.25,2.12,22m 02s,Eureka! (Santa Barbara),2,1,...,Tuesday,False,False,22.033333,5.773071,Night,2.948113,17.019667,0.000000,1
1213,2025-09-09,23.0,33.50,9.00,42.50,16.99,49m 10s,Jack in the Box (501 N Milpas St),2,2,...,Tuesday,False,False,49.166667,20.733559,Night,2.501471,51.864407,0.211765,1

In [6]:
result3 = df[df['is_weekend'] == True].sort_values(by='tip', ascending=False)
result3

,date,time,fare,tip,earnings,distance,duration,restaurant_address,points,deliveries_count,...,weekday_name,is_weekend,is_holiday,duration_min,speed_mph,part_of_day,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
1048,2025-07-05,18.5,4.58,38.68,43.26,8.67,24m 33s,Presto Pasta,6,1,...,Saturday,True,False,24.550000,21.189409,Evening,4.989619,105.727088,0.894129,0
56,2025-08-10,18.5,5.77,37.73,43.50,3.21,39 min 29 sec,Sachi Ramen (Santa Barbara),18,3,...,Sunday,True,False,39.483333,4.878008,Evening,13.551402,66.103841,0.867356,1
953,2025-08-31,20.0,7.02,31.06,38.08,12.25,55m 21s,Islands Fine Burgers & Drinks (#071 Santa Barb...,12,2,...,Sunday,True,False,55.350000,13.279133,Evening,3.108571,41.279133,0.815651,0
557,2025-09-21,19.0,23.14,25.66,48.80,11.85,1h 19m,Mandarin Palace,24,4,...,Sunday,True,False,19.000000,37.421053,Evening,4.118143,154.105263,0.525820,1
205,2025-09-13,17.0,8.14,24.17,32.31,10.10,43m 00s,Los Arroyos - Santa Barbara,12,3,...,Saturday,True,False,43.000000,14.093023,Afternoon,3.199010,45.083721,0.748066,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,2025-05-03,1.5,6.51,0.00,6.51,3.63,17m 15s,7‑Eleven (Montecito St),1,1,...,Saturday,True,False,17.250000,12.626087,Night,1.793388,22.643478,0.000000,1
293,2025-08-16,22.0,7.58,0.00,7.58,4.70,21 min 12 sec,Jack in the Box (3747 State St),1,1,...,Saturday,True,False,21.200000,13.301887,Night,1.612766,21.452830,0.000000,1
1026,2025-04-05,18.0,8.01,0.00,8.01,8.69,28m 20s,Secret Bao (1201 Anacapa St),6,1,...,Saturday,True,False,28.333333,18.402353,Evening,0.921749,16.962353,0.000000,0
1169,2025-06-08,10.5,4.05,0.00,4.05,2.96,15m 19s,Starbucks (Hollister & Storke-Goleta),3,1,...,Sunday,True,False,15.316667,11.595212,Morning,1.368243,15.865071,0.000000,0
1099,2025-09-06,11.5,30.00,0.00,30.00,19.39,1h 4m,Apple Inc – State Street R317,6,1,...,Saturday,True,False,4.000000,290.850000,Lunch,1.547189,450.000000,0.000000,0

In [7]:
result4 = df[(df['distance'].between(3, 8)) & (df['earnings'] > 15)]
result4

,date,time,fare,tip,earnings,distance,duration,restaurant_address,points,deliveries_count,...,weekday_name,is_weekend,is_holiday,duration_min,speed_mph,part_of_day,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
8,2025-08-01,1.0,4.18,11.24,15.42,3.37,32 min 10 sec,"Taco Bell, 821 N Milpas St",2,2,...,Friday,False,False,32.166667,6.286010,Night,4.575668,28.762694,0.728923,1
10,2025-08-01,8.5,4.38,15.00,19.38,5.43,23m 28s,Vons (3326),1,1,...,Friday,False,False,23.466667,13.883523,Morning,3.569061,49.551136,0.773994,0
49,2025-04-10,19.0,6.56,13.51,20.07,7.07,26m 21s,Bruxie (Santa Barbara),12,2,...,Thursday,False,False,26.350000,16.098672,Evening,2.838755,45.700190,0.673144,0
52,2025-04-10,22.0,7.25,11.85,19.10,5.50,42m 07s,"Taco Bell, 821 N Milpas St",2,2,...,Thursday,False,False,42.116667,7.835378,Night,3.472727,27.210131,0.620419,1
56,2025-08-10,18.5,5.77,37.73,43.50,3.21,39 min 29 sec,Sachi Ramen (Santa Barbara),18,3,...,Sunday,True,False,39.483333,4.878008,Evening,13.551402,66.103841,0.867356,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1162,2025-08-08,19.0,8.78,19.68,28.46,3.86,30 min 50 sec,Bruxie (Santa Barbara),18,3,...,Friday,False,False,30.833333,7.511351,Evening,7.373057,55.381622,0.691497,1
1171,2025-06-08,18.5,10.66,20.45,31.11,5.92,51m 26s,Apna Indian Kitchen (Santa Barbara),18,3,...,Sunday,True,False,51.433333,6.906027,Evening,5.255068,36.291640,0.657345,1
1172,2025-06-08,20.0,5.04,10.15,15.19,3.51,27m 34s,7‑Eleven (Montecito St),12,3,...,Sunday,True,False,27.566667,7.639661,Evening,4.327635,33.061669,0.668203,1
1179,2025-03-08,17.5,6.51,10.50,17.01,4.09,19m 12s,Apna Indian Kitchen (Santa Barbara),12,2,...,Saturday,True,False,19.200000,12.781250,Afternoon,4.158924,53.156250,0.617284,0
1190,2025-04-09,18.0,4.66,20.00,24.66,6.62,30m 35s,Secret Bao (1201 Anacapa St),6,1,...,Wednesday,False,False,30.583333,12.987466,Evening,3.725076,48.379292,0.811030,0

In [8]:
df.sort_values(by='earnings', ascending=False).head(5)

,date,time,fare,tip,earnings,distance,duration,restaurant_address,points,deliveries_count,...,weekday_name,is_weekend,is_holiday,duration_min,speed_mph,part_of_day,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
1032,2025-04-05,21.0,59.27,7.88,67.15,2.96,40m 25s,Wingstop (888 Embarcadero del Norte),13,3,...,Saturday,True,False,40.416667,4.394227,Evening,22.685811,99.686598,0.117349,0
144,2025-08-12,11.0,3.70,60.00,63.70,2.77,26m 46s,California Pizza Kitchen (719 Paseo Nuevo),3,1,...,Tuesday,False,False,26.766667,6.209215,Lunch,22.996390,142.789539,0.941915,0
360,2025-09-17,17.5,31.68,18.55,50.23,14.04,55m 44s,Sephora US (Lower State),18,3,...,Wednesday,False,False,55.733333,15.114833,Afternoon,3.577635,54.075359,0.369301,1
557,2025-09-21,19.0,23.14,25.66,48.80,11.85,1h 19m,Mandarin Palace,24,4,...,Sunday,True,False,19.000000,37.421053,Evening,4.118143,154.105263,0.525820,1
568,2025-08-22,19.5,10.02,37.25,47.27,12.32,55m 54s,California Pizza Kitchen (719 Paseo Nuevo),18,4,...,Friday,False,False,55.900000,13.223614,Evening,3.836851,50.737030,0.788026,1